language: objective-c

before_script:
  - export LANG=en_US.UTF-8 
  - gem install cocoapods
  - gem install xcpretty

script:
  - xcodebuild -workspace FMDBx.xcworkspace -scheme FMDBxTests -sdk iphonesimulator -configuration Debug test

