language: objective-c

before_install: 
  - gem install cocoapods
  - gem install xcpretty

script:
  - xcodebuild -workspace FMDBx.xcworkspace -scheme FMDBxTests -sdk iphonesimulator -configuration Debug test

